# Generated by Django 5.0.1 on 2024-02-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('kolor', 'color'), ('rozmiar', 'size'), ('podloze', 'ground')], max_length=100, verbose_name='Variation category'),
        ),
    ]
