# Generated by Django 5.0.1 on 2024-02-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=600, verbose_name='Describtion'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('kolor', 'kolor'), ('rozmiar', 'rozmiar')], max_length=100, verbose_name='Variation category'),
        ),
    ]
