"""
Django settings for zielonaszkola project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _
from django.contrib.messages import constants as messages
from decouple import config
from pathlib import Path


BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = []


INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'category',
    'accounts',
    'store',
    'carts',
    'orders',
    'i18n_switcher',
    'admin_honeypot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
]

SESSION_EXPIRE_SECONDS = 3600  # 1 hour
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_TIMEOUT_REDIRECT = 'http://127.0.0.1:8000/en/accounts/login/'

ROOT_URLCONF = 'zielonaszkola.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'category.context_processors.menu_links',
                'carts.context_processors.counter',
            ],
        },
    },
]

WSGI_APPLICATION = 'zielonaszkola.wsgi.application'

AUTH_USER_MODEL = 'accounts.Account'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]
LANGUAGE_CODE = 'pl'

LANGUAGES = [
    ('pl', _('Polish')),
    ('en', _('English')),
    ('de', _('German')),
    ('es', _('Spanish')),
]

TIME_ZONE = 'Europe/Warsaw'
DATETIME_FORMAT = 'd-m-Y H:i:s'
DATE_FORMAT = 'Y-m-d'
USE_I18N = True
USE_L10N = True
USE_TZ = True


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR /'static'
STATICFILES_DIRS = [
    'zielonaszkola/static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR /'media'

MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

REST_FRAMEWORK = {
    'NON_FIELD_ERRORS_KEY': 'Podane hasła nie są takie same',
}


# SMTP Configuration
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int) #gmail port
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD') #Wygenerowane hasło aplikacji
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)

DATETIME_FORMAT="%Y-%m-%d%H:%M:"

JAZZMIN_SETTINGS = {
    "copyright": "Jakub Jaworski",
    "show_ui_builder": False, #Customizer
    "search_model": ["auth.User"],
    "welcome_sign": _("Welcome to the admin panel login"),
    "site_logo": "images/logo_admin.jpg",
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "category.Category": "fas fa-layer-group",
        "admin_honeypot.LoginAttempt": "fas fa-bug",
        "accounts.Account": "fas fa-users",
        "accounts.UserProfile": "fas fa-user",
        "carts.Cart": "fas fa-cart-arrow-down",
        "carts.CartItem": "fas fa-bars",
        "orders.Order": "fas fa-id-card",
        "orders.OrderProduct": "fas fa-bars",
        "orders.Payment": "fas fa-credit-card",
        "store.Product": "fas fa-tree",
        "store.ReviewRating": "fas fa-star",
        "store.ProductGallery": "fas fa-image",
        "store.Variation": "fas fa-bars",
    },
    "usermenu_links": [
        {"name": _("Home"), "url": "http://127.0.0.1:8000/en/", "new_window": False},
    ],
    "topmenu_links": [
        {"name": _("Polski"), "url": 'http://127.0.0.1:8000/pl/ukrytyadmin/'},
        {"name": _("English"), "url": 'http://127.0.0.1:8000/en/ukrytyadmin/'},
        {"name": _("Spanish"), "url": 'http://127.0.0.1:8000/es/ukrytyadmin/'},
        {"name": _("Deutsh"), "url": 'http://127.0.0.1:8000/de/ukrytyadmin/'},
        {"name": _("View site"), "url": 'http://127.0.0.1:8000/en/'},
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-warning",
    "accent": "accent-lime",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "cyborg",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}


DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
