# Generated by Django 5.0.1 on 2024-02-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_orderproduct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
    ]
